# Generated by Django 4.0 on 2024-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
