# Generated by Django 4.0 on 2024-06-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_region_users_tasbih_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrayerTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('tong', models.CharField(max_length=255)),
                ('quyosh', models.CharField(max_length=255)),
                ('peshin', models.CharField(max_length=255)),
                ('asr', models.CharField(max_length=255)),
                ('shom', models.CharField(max_length=255)),
                ('hufton', models.CharField(max_length=255)),
            ],
        ),
    ]
