# Generated by Django 4.0 on 2024-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dailyprayertimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tasbih_mode',
            field=models.IntegerField(blank=True, default=33, null=True),
        ),
    ]
